Rewrite the script based on scale_jpeg_web
Rewrite the script in more compact way

diff --git a/exif_rename b/exif_rename
--- a/exif_rename
+++ b/exif_rename
@@ -1,56 +1,25 @@
 #!/bin/bash
+set -e
+while [ -n "${1}" ]; do
+    INFILE="${1}"
+    date=$(exiftool -d %Y%m%d-%H%M%S -p '$CreateDate' "$INFILE")
+    OUTFILE="${date}.jpg"
 
-while [ "$*" != "" ]
-do
-    oldFileName="$1"
+    if [ "${date}" == "" ]; then
+	    echo "${INFILE} unmodified (couldn't read exif data)"
+	elif [ "${OUTFILE}" == "${INFILE}" ]; then
+	    echo "${INFILE} unmodified (file name already matches exif data)"
+    else
+        i=1
+        while [ -e "${OUTFILE}" ]; do
+            OUTFILE="${date}-${i}.jpg"
+            let i++
+        done
+
+        echo "Rename ${INFILE} to ${OUTFILE}"
+        mv "${INFILE}" "${OUTFILE}"
+    fi
+
     shift
-    dirname=`dirname ${oldFileName}`
-    basename=`basename ${oldFileName}`
-
-    oldFileName="${dirname}/${basename}"
-    createDate=`exiftool -CreateDate "${oldFileName}"`
-    date=`echo ${createDate} | sed -e 's|^Create Date : \([0-9][0-9][0-9][0-9]\):\([0-9][0-9]\):\([0-9][0-9]\) \([0-9][0-9]\):\([0-9][0-9]\):\([0-9][0-9]\).*$|\1\2\3-\4\5\6|; s|:||g; s| |-|g'`
-
-    # If the file does not have an EXIF create date, we won't touch the file.
-    if [ "${date}" == '' ]
-    then
-	echo "${oldFileName} unmodified"
-	break;
-    fi
-
-    # If the create date as extracted via exiftool is not in the
-    # expected format, we won't touch the file.
-    check=`echo ${date} | sed -e 's|^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]$||'`
-    if [ "${check}" != '' ]
-    then
-	echo "${oldFileName} unmodified"
-	break;
-    fi
-
-    i=1;
-    renamed=0
-    while [ ${renamed} -eq 0 ]
-    do
-	if [ $i -eq 1 ]
-	then
-	    extension=""
-	else
-	    extension="-${i}"
-	fi
-	newFileName="${dirname}/${date}${extension}.jpg"
-	if [ -e ${newFileName} ]
-	then
-	    i=`expr ${i} + 1`
-	else
-	    if [ "${oldFileName}" == "${newFileName}" ]
-	    then
-		echo "${oldFileName} unmodified"
-	    else
-		mv "${oldFileName}" "${newFileName}"
-		echo "${oldFileName} renamed to ${newFileName}"
-	    fi
-	    renamed=1
-	fi
-    done
 done
 
